name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing dep
      run: |
        pip install sphinx_rtd_theme
        
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./Software engineering/1.1"
    # Publish built docs to gh-pages branch.

