name: doc-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - uses: ammaraskar/sphinx-action@master
          with:
            docs-folder: "docs/"